<!DOCTYPE html>
<html lang="en">
    <head>
        <title> Korean papa in China </title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
    </head>
    <body>
      <nav>
      <img src="koreandad-logo.webp" alt="Korean dad logo" class="logo">
      <div class="links">
        <a>Portfolio</a>
        <a>Team</a>
        <a>Contacts</a>
        <button type="button">Contact Us</button>
        <div class="burgermenu"><img src="./resources/menu.png"></div>
      </div>
    </nav>
      <section class="mission">
    <p> Mission </p>
    <p> K-Dad is a trusted wholesale distributor specializing in connecting high-quality products from China with businesses in Korea. Our mission is to provide seamless and efficient supply chain solutions, empowering our partners with reliable sourcing and competitive pricing. With a strong foundation in family values and business integrity, we are committed to fostering long-term relationships with our customers, ensuring their success and satisfaction.
    </p>
      </section>
        <section class="products">
              <h2>Our Products</h2>
    <ul>
      <li>
        product1 
      </li>
      <li>
        product2 
      </li>
      <li>
        product3 
      </li>
      <li>
        product4 
      </li>
      <li>
        product5 
      </li>
    </ul>
      </section>
        <section class="staffs">
<p>
  Our team
   <ul>
      <li>
        STAFF1 
      </li>
      <li>
        STAFF2 
      </li>
   </ul>
</p>
  </section>
    </body>
